name: Python Tests

on: [push]

jobs:

  test:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        platform: [ubuntu-latest]

    steps:
    - name: Install system dependencies
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install libssl-dev libxmlsec1 libxmlsec1-dev libxmlsec1-openssl libxslt1-dev pkg-config
    - name: Install system dependencies
      if: matrix.platform == 'macos-latest'
      run: |
        brew install libxmlsec1 libxslt pkgconfig
 
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up rye
      uses: atu4403/setup-rye-multiOS@v1
    - name: Sync dependencies using rye
      run: |
        rye pin ${{ matrix.python-version }}
        rye sync

    - name: Test with pytest
      run: |
        rye run pytest